services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: plataforma-calendario-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: plataforma_calendario
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - plataforma-network
    # Healthcheck para PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d plataforma_calendario"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plataforma-calendario-backend
    restart: unless-stopped
    working_dir: /var/www
    user: 'www'
    volumes:
      - ./backend:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=plataforma_calendario
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
    networks:
      - plataforma-network
    ports:
      - "8000:9000"  # Mapear puerto 8000 externo al 9000 interno
    depends_on:
      db:
        condition: service_healthy # Espera a que la BD esté lista

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plataforma-calendario-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - plataforma-network
    command: npm run dev
    # Healthcheck para el servidor de desarrollo de Next.js
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servidor web Nginx
  nginx:
    image: nginx:alpine
    container_name: plataforma-calendario-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - plataforma-network
    depends_on:
      backend:
        condition: service_started # El backend es rápido, con 'started' es suficiente
      frontend:
        condition: service_healthy # Espera a que Next.js esté listo

volumes:
  db_data:
    driver: local

networks:
  plataforma-network:
    driver: bridge